### ISSUE TITLE
Zero address detector is not correct

### ISSUE THREAD

**Issue by deuszx** [CoinFabrik/scout#130]
https://coinfabrik.github.io/scout/docs/detectors/zero-or-test-address

Is not correct in Substrate. See https://substrate.stackexchange.com/questions/982/why-does-the-all-0-public-key-have-a-known-private-key-in-sr25519-and-ed25519

**Comment by aon** [comment]
Thanks for the input! We'll change the documentation right away.

**Comment by deuszx** [comment]
@aon you haven't updated the detector.

**Comment by aon** [comment]
Hi @deuszx. I'm not sure what you mean with the detector. I checked the description message and the code and it looks correct to me. Let me know!

**Comment by deuszx** [comment]
At the very least [this](https://github.com/CoinFabrik/scout/blob/main/detectors/zero-or-test-address/src/lib.rs#L31) comment is not correct. 

But more generally speaking - where previously it was OK-ish to send funds to ZERO_ADDRESS (it _may_ have been incorrect, b/c they were being locked), I think now it's  _wrong_ to USE ZERO_ADDRESS _anywhere_ in the contract. 

For example, ZERO_ADDRESS was used for "locking tokens forever" by various Ethereum projects. Take Uniswap - ZERO_ADDRESS is used as recipient of certain type of "dust" tokens, minted when the pool is initialised for the first time.

You can see how many tokens are locked there https://etherscan.io/address/0x0000000000000000000000000000000000000000 . Some are certainly locked "by mistake" but some are not and were sent deliberately there with an intent to be unrecoverable w/o _burning_ them (which would affect the total supply and tokenomics of the project).

**Comment by deuszx** [comment]
@aon , any updates on this?

**Comment by faculerena** [comment]
The detector is focused on warning when setting an address, maybe as an admin, or some other field in memory is not checked for a empty/zero value. Setting the admin to zero (for this case an incorrect address too, but a zero-address error is easier to make) can cause a lockout.

**Comment by deuszx** [comment]
I'm not sure I understand this comment @faculerena ... To me it's much better to "err on the safer side" of things and not allow for usage of ZERO_ADDRESS anywhere in the code. I can't imagine it being a correct value under any circumstences.

Since these detectors are not "hard errors" but just warnings, we should warn about any potential issue and for ZERO_ADDRESS case it's actually everything.

**Comment by faculerena** [comment]
This detector is equivalent to this https://github.com/crytic/slither/wiki/Detector-Documentation#missing-zero-address-validation. We could extend or make another detector. I will talk to the team.

**Comment by faculerena** [comment]
Following in #145. Thanks for the insight and recomendations!
