### ISSUE TITLE
Add detector for misuse of `set_contract_storage(KEY)`

### ISSUE THREAD

**Issue by deuszx** [CoinFabrik/scout#137]
Every contract has its own "storage space" where it can set/get values from. The API is (more or less): `ink::env::set_contract_storage(key, value)`. Sometimes, users choose to set contract elements' keys manually, like `ManualKey<0xDEADBEEF>` ([example](https://github.com/Cardinal-Cryptography/aleph-node/blob/main/contracts/simple_dex/lib.rs#L144)) - this pattern is becoming more and more prevalent in contracts that support upgradeability (by storing data under z separate key, we're decoupling contract's state from its logic - allowing for logic upgrades w/o the need of migrating the data).

This approach is flexible but also dangerous, contract author could (mistakenly) overwrite the same key, destroying the previous data or even bricking the contract.

A detector that finds multiple usages of the same key in `set_contract_storage` could raise a warning about potentially dangerous code.

Follows https://swcregistry.io/docs/SWC-124/

**Comment by faculerena** [comment]
This is an upgrade of the [set_contract_storage](https://github.com/CoinFabrik/scout/tree/main/detectors/set-contract-storage) detector.

**Comment by faculerena** [comment]
Following in #149. Closing this. Thanks!
