### ISSUE TITLE
Mutable `Lazy::get` not `set`.

### ISSUE THREAD

**Issue by deuszx** [CoinFabrik/scout#170]
I'm not sure if this is already "detectable" or not so I'm posting here anyway and you let me know if it's new.

There's a certain pattern that I see popping up around usage of `Lazy` wrapper. Data inside it is not automatically "flushed" to the underlying storage so it's too easy to miss it. Consider the following:
```rust
struct Data {
  total_shares: u128
}

struct MyContract {
  data: Lazy<Data>,
}

impl MyContract {
  #[ink(message)]
  pub fn foo(&mut self, t: u128) {
     let mut s = self.data.get();
     s.total_shares += t;
  }
}
```
At the end of `foo` we still have "pre-foo" state in `data` since it's required to call `Lazy::set` explicitly:
```rust
impl MyContract {
  #[ink(message)]
  pub fn foo(&mut self, t: u128) {
     let mut s = self.data.get();
     s.total_shares += t;
     self.data.set(&s);
  }
}
```

It would be great to have a detector for a mutable usage of `Lazy` type that is not followed by `Lazy::set`.

Thanks!

**Comment by faculerena** [comment]
Closed by: #265
