### ISSUE TITLE
`AutoKey` with `Lazy` and `set_code_hash`. 

### ISSUE THREAD

**Issue by deuszx** [CoinFabrik/scout#171]
Following on https://use.ink/datastructures/storage-layout#manual-vs-automatic-key-generation

and the **Tip!**:
> Using `ManualKey` instead of `AutoKey` might be especially desirable for upgradable contracts, as using `AutoKey` might result in a different storage key for the same field in a newer version of the contract. This may break your contract after an upgrade 😱!

We might want to add a detector for the case when:
1. There's `Lazy` field used with `AutoKey`
2. There's a `set_code_hash` function in the contract that upgrades it.

warn users about the potential issues & suggest using `ManualKey`.

**Comment by faculerena** [comment]
Closed by #243. This is now a detector in main.
