### ISSUE TITLE
Usage of cached `Lazy` state.

### ISSUE THREAD

**Issue by deuszx** [CoinFabrik/scout#225]
Consider the following (pseudocode):

```rust
struct Contract {
  s: Lazy<Test>
}

struct Test {
  v: bool
}

impl Contract {
  fn flip() {
    let old = self.s.get();
    old.v = !old.v;
    self.s.set(old)
  }

  fn flip_internal() {
    let old = self.s.get();
    self._internal();
    self.s.set(old); <---- !!! doesn't see changes from _internal !!!
  }
  
  fn _internal() {
    let old = self.s.get();
    old.v = !old.v;
    self.s.set(old)
  }
}
```

When we enter `flip_internal` we cache `old = self.s.get()`, then call into `_internal` which also reads AND MODIFIES the same `Lazy<_>`, we return back to `flip_internal` where the method sees _cached version_ of `self.s` meaning it doesn't know about the changes made in `_internal`. It then overwrites them all.

This may seem obvious in this simple example but when contracts grow the logic flows may not be so clear anymore and mistakes can happen.

It would be nice to have a detector for it, not yet sure how that could be realised.

**Comment by faculerena** [comment]
Closed by: #265
