### ISSUE TITLE
Add filtering, excluding and listing for detector categories in `cargo-scout`

### ISSUE THREAD

**Issue by aon** [CoinFabrik/scout#23]
## Description
Add options to allow:
- filtering by detector categories
- exclusion by detector categories
- listing existing detector categories

## Acceptance Criteria
Implements the following commands:

- `cargo scout –-filter-by-categories <CATEGORY_LIST_SEPARATED_BY_COMAS>`
- `cargo scout –-exclude-categories <CATEGORY_LIST_SEPARATED_BY_COMAS>`
- `cargo scout -–list-categories`

## Estimate
3

## Sprint number
1

**Comment by faculerena** [comment]
This is implemented as the `--profile` flag. Could be updated to categories but it's not planned.
