### ISSUE TITLE
Blockchain Dependency Not Found

### ISSUE THREAD

**Issue by ihtisham-sudo** [CoinFabrik/scout#242]
Trying to run cargo scout-audit command on a project but it terminates with an error: 
```
cargo scout-audit

thread 'main' panicked at /home/ihtishamsudo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo-scout-audit-0.2.4/src/startup.rs:155:10:
Blockchain dependency not found
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
couldn't find help from the internet.

**Comment by ihtisham-sudo** [comment]
adding on :
installation is being done with tweaks i.e using nightly for installing scout-audit because with stable I give error :
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /home/ihtishamsudo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/scout-audit-internal-0.2.4/src/lib.rs:1:1
  |
1 | #![feature(const_trait_impl)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `scout-audit-internal` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `cargo-scout-audit v0.2.4`, intermediate artifacts can be found at `/tmp/cargo-installpbgeQ5`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

**Comment by faculerena** [comment]
Hello! Yes, we should update the docs to add the `+nightly` to the install instructions. 

On the "blockchain dependency not found" issue, are you running Scout on a smart contract? The smart contract folder should have a `Cargo.toml` inside that has either `ink` or `soroban-sdk` as a dependency. If not, Scout does not know which set of linters needs to run.
